#
#       Configuration File
#

# -- User settings --#

[SETTINGS]
experiment_name = 'pr_scale_time_stdscaler_np_worog_gpufix_bs50_ERAI_atos_v2'

#'upscale', 'direct'
downscale mode = 'direct' 

#July
file_filter = {'file_x': "6hr_[0-9]", 'file_y': "6hr_[0-9]", 'file_const': 'fx'}
#file_filter_const = 'fx' 

path_main = '/ec/res4/scratch/smf/HCLIMAI/Emilia_Romagna/SG/'
path_x = {'file_mode': 'one_var_per_file',
#          #'path': ['/ec/res4/scratch/smf/HCLIMAI/Emilia_Romagna/cropped/ICHEC-EC-EARTH_HIST/']}
          'path': ['/perm/smf/HCLIMAI/Emilia_Romagna/cropped/ECMWF-ERAINT/']}
path_y = {'file_mode': 'one_var_per_file', 
#          'path': ['/ec/res4/scratch/smf/HCLIMAI/Emilia_Romagna/cropped/ICHEC-EC-EARTH_HIST/']} 
          'path': ['/perm/smf/HCLIMAI/Emilia_Romagna/cropped/ECMWF-ERAINT/']}

variables = {
    'low resolution': {
        'resolution': '12km',
        'freq': '6hr',
        #              'ps', 'mrso', \
        #              'pr', \
        #              'tas', \
        'var names': [ \
                      'phi500', 'phi700', 'phi850', 'phi950', \
	              'hus500', 'hus700', 'hus850', 'hus950', \
	              'ta500', 'ta700', 'ta850', 'ta950', \
	              'ua500', 'ua700', 'ua850', 'ua950', \
	              'va500', 'va700', 'va850', 'va950', \
                     ] }, \
    'constant fields': {
        'resolution': '3km',
        'freq': 'fx',
        'var names': ['orog'] }, \
    'high resolution': {
        'resolution': '3km',
        'freq': '6hr',
        'var names': ['pr'] } 
    }
#        'var names': ['phi950', 'hus950', 'ua950', 'va950', 'pr'] }, \
#        'var names': ['orog'] }, \
#        'var names': ['pr'] }, \
#        ['phi500', 'phi700', 'phi850', 'phi950', \
#	'hus500', 'hus700', 'hus850', 'hus950', \
#	'ta500', 'ta700', 'ta850', 'ta950', \
#	'ua500', 'ua700', 'ua850', 'ua950', \
#	'va500', 'va700', 'va850', 'va950', 'pr'] }, \

# Regions to extract: Empty or list [reg1, reg2, ...
#regions = ['Fenno-Scandinavia', 'East Europe', 'Mediterranean Sea']
coordinates_of_detection_area = {'lonmin':16, 'lonmax':19, 'latmin':58, 'latmax':60} 


time_range = {
    'step_hours': 6,
#    'all_lowres': {'start_date': ["1995-01-01 00:00"], 'end_date': ["2005-12-31 24:00"]}, 
#    'all_highres': {'start_date': ["1995-01-01 00:00"], 'end_date': ["2005-12-31 24:00"]}, 
#    'target': {'start_date': ["1996-01-01 00:00"], 'end_date': ["2005-12-31 24:00"]},
#    'test': {'start_date': ["2005-01-01 00:00"], 'end_date': ["2005-12-31 24:00"]},
    'all_lowres': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"]}, 
    'all_highres': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"]}, 
    'target': {'start_date': ["2000-01-01 00:00"], 'end_date': ["2009-12-31 24:00"]},
    'test': {'start_date': ["2009-01-01 00:00"], 'end_date': ["2009-12-31 24:00"]},
    }


[STATISTICS]
# Statistics to calculate;
# METHOD: SG, ViT, Swin, EffNetV2
stats = {
        'SRGAN': {'METHOD': 'SG', 'BATCH_SIZE': 50, 'EPOCHS': 100, 'EPOCH_INIT': 0, \
            'VALIDATION_SPLIT': 0.1, 'RANDOM_STATE': 24}, 
        'TRAINING': {'SUBSAMPLING_LR': 4, 'N_RES_BLOCK': 8, 'NX': 424, 'NY': 352, \
            'LEARNING_RATE': {'GENERATOR': 1e-4, 'DISCRIMINATOR': 1e-4}, 'DROPOUT_RATE': -1, 'EARLY_STOP': False, 'DATA_AUGMENTATION': False, \
            'DISABLE_PARALLEL': False},
        'RUNNING_MODE': {'TRAINING_MODE': True, 'PREDICTION_MODE': True, 'PRETRAINED_PATH': ''}, \
        'PREPROCESS': {'SCALER_DEF': 'StandardScaler', 'SCALER_HUS': 'StandardScaler', 'SCALE_METHOD': 'scale_over_time'}, \
        'LOSS': {'WEIGHT_ADVERSARIAL': 1e-5, 'WEIGHT_CONTENT': 1.0, 'WEIGHT_CROSS_ENTROPY': 0.2, 'LAMBDA_CORR': 0.0, \
            'CONTENT_LOSS_FUNC': 'MSE', 'LOSSES_REDUCTION': 'NONE', 'LABEL_SMOOTHING_REAL': 1.0, \
            'DISCRIMINATOR_NOISE_STD': 0.0, 'DISCRIMINATOR_LABEL_NOISE': 1.0}, \ 
    }


[PLOTTING]
# Do validation plots -- a standard set of plots for general validation 
validation plot = True

# Map plot settings
# Example of configuration displayed here; for default settings set all properties to empty dictionaries -- {}
map configure = {'proj': 'stere', 'res': 'l', 'zoom': 'geom', 'zoom_geom': [1700000, 2100000], 'lon_0': 16.5, 'lat_0': 63}
map grid setup = {'axes_pad': 0.5, 'cbar_mode': 'each', 'cbar_location': 'right',
              	  'cbar_size': '5%%', 'cbar_pad': 0.03}
map kwargs = {'filled': True, 'mesh': True}

# Line plot settings
line grid setup = {'axes_pad': (11., 6.)}
line kwargs = {'lw': 2.5}


[CLUSTER]
# Local pc or SLURM are implemented.

# local/slurm
cluster type = slurm

# SLURM
# Default (not needed to set here) is set to a normal compute node for Bi, 
# which has 64GB memory. And walltime is set to 1 hour.
# If fat node is requested in job_extra, increase memory to 256GB.
nodes = 1

# extra key word arguments for chosen cluster
cluster kwargs = {'walltime': '02:00:00'}
# cluster kwargs = {'walltime': '02:00:00', 'memory': '256GB', 'job_extra': ['-C fat']}
