base_dir: "/nobackup/rossby26/users/sm_fuxwa/AI/Emilia_Romagna/cropped/"

variable: "pr"

data_path:
  input_lowres_nc:  "${base_dir}/12km/6hr/${variable}/${variable}_12km_6hr_200001010300-200912312100.nc"
  input_highres_nc: "${base_dir}/3km/6hr/${variable}/${variable}_3km_6hr_200001010300-200912312100.nc"
  output_interp_nc: "${base_dir}/3km_interp/6hr/${variable}/${variable}_3km_interp_6hr_200001010300-200912312100.nc"
  output_diff_nc:   "${base_dir}/3km_interp/6hr/${variable}/${variable}_3km_difference_6hr_200001010300-200912312100.nc"




