#
#       Configuration File for Extreme_Event_Detection
#
#  	-- Modify the []-sections with user defined settings
#
# 	*** N.B. ***
# 	Please read through RCAT documentation on how to set the configurations:
# 	https://extreme-event-detection.readthedocs.io/en/latest/
#


# -- User settings --#

[SETTINGS]
experiment_name = 'tas_val0.1'

#'upscale', 'direct'
downscale mode = 'direct' 

#July
file_filter = 'hr_2000' 
file_filter_const = 'fx' 

path_main = '/project/project_465000527/wangfuxi/AI_data/Test_Domain/SG/'
path_x = '/project/project_465000527/wangfuxi/AI_data/Test_Domain/'
path_y = '/project/project_465000527/wangfuxi/AI_data/Test_Domain/'

variables = {
    'low resolution': {
        'resolution': '12km',
        'freq': '6hr',
        #              'ps', 'mrso', \
        #              'pr', \
        #              'mrso', \
        #] }, \
        'var names': [ \
                      'phi500', 'phi700', 'phi850', 'phi950', \
	              'hus500', 'hus700', 'hus850', 'hus950', \
	              'ta500', 'ta700', 'ta850', 'ta950', \
	              'ua500', 'ua700', 'ua850', 'ua950', \
	              'va500', 'va700', 'va850', 'va950', \
	             ] }, \
    'constant fields': {
        'resolution': '3km',
        'freq': 'fx',
        'var names': ['orog'] }, \
    'high resolution': {
        'resolution': '3km',
        'freq': '6hr',
        'var names': ['tas'] } 
    }
#        'var names': ['phi950', 'hus950', 'ua950', 'va950', 'pr'] }, \
#        'var names': ['orog'] }, \
#        'var names': ['pr'] }, \
#        ['phi500', 'phi700', 'phi850', 'phi950', \
#	'hus500', 'hus700', 'hus850', 'hus950', \
#	'ta500', 'ta700', 'ta850', 'ta950', \
#	'ua500', 'ua700', 'ua850', 'ua950', \
#	'va500', 'va700', 'va850', 'va950', 'pr'] }, \

# Regions to extract: Empty or list [reg1, reg2, ...
#regions = ['Fenno-Scandinavia', 'East Europe', 'Mediterranean Sea']
coordinates_of_detection_area = {'lonmin':16, 'lonmax':19, 'latmin':58, 'latmax':60} 


[STATISTICS]
# Statistics to calculate;
# METHOD: SG, ViT, Swin, EffNetV2
stats = {
        'SRGAN': {'METHOD': 'SG', 'BATCH_SIZE': 50, 'EPOCHS': 100, 'EPOCH_INIT': 0, \
            'TEST_SIZE': 1460, 'VALIDATION_SPLIT': 0.1, 'RANDOM_STATE': 24}, 
        'TRAINING': {'SUBSAMPLING_LR': 4, 'N_RES_BLOCK': 8, 'NX': 104, 'NY': 88, \
            'LEARNING_RATE': 1e-4, 'DROPOUT_RATE': 99, 'EARLY_STOP': False, 'DATA_AUGMENTATION': False},
#        'TRAINING': {'SUBSAMPLING_LR': 4, 'N_RES_BLOCK': 8, 'INPUT_CHANNELS': 21, 'OUTPUT_CHANNELS': 1, 'NX': 104, 'NY': 88},
    }


[PLOTTING]
# Do validation plots -- a standard set of plots for general validation 
validation plot = True

# Map plot settings
# Example of configuration displayed here; for default settings set all properties to empty dictionaries -- {}
map configure = {'proj': 'stere', 'res': 'l', 'zoom': 'geom', 'zoom_geom': [1700000, 2100000], 'lon_0': 16.5, 'lat_0': 63}
map grid setup = {'axes_pad': 0.5, 'cbar_mode': 'each', 'cbar_location': 'right',
              	  'cbar_size': '5%%', 'cbar_pad': 0.03}
map kwargs = {'filled': True, 'mesh': True}

# Line plot settings
line grid setup = {'axes_pad': (11., 6.)}
line kwargs = {'lw': 2.5}


[CLUSTER]
# Local pc or SLURM are implemented.

# local/slurm
cluster type = slurm

# SLURM
# Default (not needed to set here) is set to a normal compute node for Bi, 
# which has 64GB memory. And walltime is set to 1 hour.
# If fat node is requested in job_extra, increase memory to 256GB.
nodes = 1

# extra key word arguments for chosen cluster
cluster kwargs = {'walltime': '02:00:00'}
# cluster kwargs = {'walltime': '02:00:00', 'memory': '256GB', 'job_extra': ['-C fat']}
